apiVersion: v1
kind: Secret
metadata:
  name: support-etcd
type: Opaque
stringData:
  # Override this in your overlay with the actual etcd endpoint.
  servers: "http://etcd.milo-system.svc.cluster.local:2379"
