// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateNetworkingDatumapisComV1Alpha1ConnectorClassData,
  CreateNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  CreateNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassData,
  DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassErrors,
  DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassResponses,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementData,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementErrors,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementResponses,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorData,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorErrors,
  DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorResponses,
  DeleteNetworkingDatumapisComV1Alpha1ConnectorClassData,
  DeleteNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  DeleteNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesData,
  ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesErrors,
  ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesResponses,
  ListNetworkingDatumapisComV1Alpha1ConnectorClassData,
  ListNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  ListNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesData,
  ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesErrors,
  ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesResponses,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  ListNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassData,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusData,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
  PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
  PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassData,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusData,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
  ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
  ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassData,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusData,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
  ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorData,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
  ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind ConnectorAdvertisement
 */
export const listNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesResponses,
    ListNetworkingDatumapisComV1Alpha1ConnectorAdvertisementForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectoradvertisements', ...options });

/**
 * delete collection of ConnectorClass
 */
export const deleteNetworkingDatumapisComV1Alpha1CollectionConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassResponses,
    DeleteNetworkingDatumapisComV1Alpha1CollectionConnectorClassErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses', ...options });

/**
 * list objects of kind ConnectorClass
 */
export const listNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    ListNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses', ...options });

/**
 * create a ConnectorClass
 */
export const createNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    CreateNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ConnectorClass
 */
export const deleteNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    DeleteNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ConnectorClass
 */
export const readNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    ReadNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}', ...options });

/**
 * partially update the specified ConnectorClass
 */
export const patchNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    PatchNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ConnectorClass
 */
export const replaceNetworkingDatumapisComV1Alpha1ConnectorClass = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassResponses,
    ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified ConnectorClass
 */
export const readNetworkingDatumapisComV1Alpha1ConnectorClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
    ReadNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}/status', ...options });

/**
 * partially update status of the specified ConnectorClass
 */
export const patchNetworkingDatumapisComV1Alpha1ConnectorClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
    PatchNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified ConnectorClass
 */
export const replaceNetworkingDatumapisComV1Alpha1ConnectorClassStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusResponses,
    ReplaceNetworkingDatumapisComV1Alpha1ConnectorClassStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/connectorclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * list objects of kind Connector
 */
export const listNetworkingDatumapisComV1Alpha1ConnectorForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesResponses,
    ListNetworkingDatumapisComV1Alpha1ConnectorForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha1/connectors', ...options });

/**
 * delete collection of ConnectorAdvertisement
 */
export const deleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementResponses,
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements',
    ...options,
  });

/**
 * list objects of kind ConnectorAdvertisement
 */
export const listNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    ListNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements',
    ...options,
  });

/**
 * create a ConnectorAdvertisement
 */
export const createNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ConnectorAdvertisement
 */
export const deleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ConnectorAdvertisement
 */
export const readNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}',
    ...options,
  });

/**
 * partially update the specified ConnectorAdvertisement
 */
export const patchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ConnectorAdvertisement
 */
export const replaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisement = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementResponses,
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified ConnectorAdvertisement
 */
export const readNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified ConnectorAdvertisement
 */
export const patchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified ConnectorAdvertisement
 */
export const replaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusResponses,
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorAdvertisementStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectoradvertisements/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Connector
 */
export const deleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorResponses,
    DeleteNetworkingDatumapisComV1Alpha1CollectionNamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors',
    ...options,
  });

/**
 * list objects of kind Connector
 */
export const listNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    ListNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors',
    ...options,
  });

/**
 * create a Connector
 */
export const createNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    CreateNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Connector
 */
export const deleteNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    DeleteNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Connector
 */
export const readNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}',
    ...options,
  });

/**
 * partially update the specified Connector
 */
export const patchNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Connector
 */
export const replaceNetworkingDatumapisComV1Alpha1NamespacedConnector = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorResponses,
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Connector
 */
export const readNetworkingDatumapisComV1Alpha1NamespacedConnectorStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
    ReadNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Connector
 */
export const patchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
    PatchNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Connector
 */
export const replaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusResponses,
    ReplaceNetworkingDatumapisComV1Alpha1NamespacedConnectorStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha1/namespaces/{namespace}/connectors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
