// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as ClientOptions, TDataShape } from '../shared/client';
import { client as _heyApiClient } from '../shared/client.gen';
import type {
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipData,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipErrors,
  ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
  ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
  PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesData,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesResponses,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesErrors,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationData,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationErrors,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationData,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  ListResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  CreateResourcemanagerMiloapisComV1Alpha1OrganizationData,
  CreateResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  CreateResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  DeleteResourcemanagerMiloapisComV1Alpha1OrganizationData,
  DeleteResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationData,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationData,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationData,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusData,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
  ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusData,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
  PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusData,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectData,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectErrors,
  ListResourcemanagerMiloapisComV1Alpha1ProjectData,
  ListResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  ListResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  CreateResourcemanagerMiloapisComV1Alpha1ProjectData,
  CreateResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  CreateResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  DeleteResourcemanagerMiloapisComV1Alpha1ProjectData,
  DeleteResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  DeleteResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectData,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectData,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectData,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectErrors,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusData,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
  ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusData,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
  PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusData,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
  ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of OrganizationMembership
 */
export const deleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionNamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships',
    ...options,
  });
};

/**
 * list objects of kind OrganizationMembership
 */
export const listResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    ListResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships',
    ...options,
  });
};

/**
 * create an OrganizationMembership
 */
export const createResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).post<
    CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    CreateResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an OrganizationMembership
 */
export const deleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified OrganizationMembership
 */
export const readResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}',
    ...options,
  });
};

/**
 * partially update the specified OrganizationMembership
 */
export const patchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified OrganizationMembership
 */
export const replaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembership = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified OrganizationMembership
 */
export const readResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
    ReadResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified OrganizationMembership
 */
export const patchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
    PatchResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified OrganizationMembership
 */
export const replaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1NamespacedOrganizationMembershipStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/namespaces/{namespace}/organizationmemberships/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind OrganizationMembership
 */
export const listResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).get<
    ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesResponses,
    ListResourcemanagerMiloapisComV1Alpha1OrganizationMembershipForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizationmemberships',
    ...options,
  });
};

/**
 * delete collection of Organization
 */
export const deleteResourcemanagerMiloapisComV1Alpha1CollectionOrganization = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationData,
    ThrowOnError
  >
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionOrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations',
    ...options,
  });
};

/**
 * list objects of kind Organization
 */
export const listResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    ListResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations',
    ...options,
  });
};

/**
 * create an Organization
 */
export const createResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    CreateResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an Organization
 */
export const deleteResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified Organization
 */
export const readResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    ReadResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}',
    ...options,
  });
};

/**
 * partially update the specified Organization
 */
export const patchResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    PatchResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified Organization
 */
export const replaceResourcemanagerMiloapisComV1Alpha1Organization = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified Organization
 */
export const readResourcemanagerMiloapisComV1Alpha1OrganizationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
    ReadResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified Organization
 */
export const patchResourcemanagerMiloapisComV1Alpha1OrganizationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
    PatchResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified Organization
 */
export const replaceResourcemanagerMiloapisComV1Alpha1OrganizationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1OrganizationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/organizations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of Project
 */
export const deleteResourcemanagerMiloapisComV1Alpha1CollectionProject = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1CollectionProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects',
    ...options,
  });
};

/**
 * list objects of kind Project
 */
export const listResourcemanagerMiloapisComV1Alpha1Project = <ThrowOnError extends boolean = false>(
  options?: Options<ListResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ListResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    ListResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects',
    ...options,
  });
};

/**
 * create a Project
 */
export const createResourcemanagerMiloapisComV1Alpha1Project = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CreateResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    CreateResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a Project
 */
export const deleteResourcemanagerMiloapisComV1Alpha1Project = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    DeleteResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified Project
 */
export const readResourcemanagerMiloapisComV1Alpha1Project = <ThrowOnError extends boolean = false>(
  options: Options<ReadResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    ReadResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}',
    ...options,
  });
};

/**
 * partially update the specified Project
 */
export const patchResourcemanagerMiloapisComV1Alpha1Project = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    PatchResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified Project
 */
export const replaceResourcemanagerMiloapisComV1Alpha1Project = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceResourcemanagerMiloapisComV1Alpha1ProjectData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1ProjectResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1ProjectErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified Project
 */
export const readResourcemanagerMiloapisComV1Alpha1ProjectStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
    ReadResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified Project
 */
export const patchResourcemanagerMiloapisComV1Alpha1ProjectStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
    PatchResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified Project
 */
export const replaceResourcemanagerMiloapisComV1Alpha1ProjectStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusResponses,
    ReplaceResourcemanagerMiloapisComV1Alpha1ProjectStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/resourcemanager.miloapis.com/v1alpha1/projects/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
