// This file is auto-generated by @hey-api/openapi-ts
import type {
  CreateAuthorizationV1NamespacedLocalSubjectAccessReviewResponse,
  CreateAuthorizationV1SelfSubjectAccessReviewResponse,
  CreateAuthorizationV1SelfSubjectRulesReviewResponse,
  CreateAuthorizationV1SubjectAccessReviewResponse,
} from './types.gen';

export const createAuthorizationV1NamespacedLocalSubjectAccessReviewResponseTransformer = async (
  data: any
): Promise<CreateAuthorizationV1NamespacedLocalSubjectAccessReviewResponse> => {
  data = ioK8sApiAuthorizationV1LocalSubjectAccessReviewSchemaResponseTransformer(data);
  return data;
};

const ioK8sApiAuthorizationV1LocalSubjectAccessReviewSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer = (data: any) => {
  if (data.creationTimestamp) {
    data.creationTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.creationTimestamp
    );
  }
  if (data.deletionGracePeriodSeconds) {
    data.deletionGracePeriodSeconds = BigInt(data.deletionGracePeriodSeconds.toString());
  }
  if (data.deletionTimestamp) {
    data.deletionTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.deletionTimestamp
    );
  }
  if (data.generation) {
    data.generation = BigInt(data.generation.toString());
  }
  if (data.managedFields) {
    data.managedFields = data.managedFields.map((item: any) => {
      return ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer(item);
    });
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer = (data: any) => {
  if (data.time) {
    data.time = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(data.time);
  }
  return data;
};

export const createAuthorizationV1SelfSubjectAccessReviewResponseTransformer = async (
  data: any
): Promise<CreateAuthorizationV1SelfSubjectAccessReviewResponse> => {
  data = ioK8sApiAuthorizationV1SelfSubjectAccessReviewSchemaResponseTransformer(data);
  return data;
};

const ioK8sApiAuthorizationV1SelfSubjectAccessReviewSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  return data;
};

export const createAuthorizationV1SelfSubjectRulesReviewResponseTransformer = async (
  data: any
): Promise<CreateAuthorizationV1SelfSubjectRulesReviewResponse> => {
  data = ioK8sApiAuthorizationV1SelfSubjectRulesReviewSchemaResponseTransformer(data);
  return data;
};

const ioK8sApiAuthorizationV1SelfSubjectRulesReviewSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  return data;
};

export const createAuthorizationV1SubjectAccessReviewResponseTransformer = async (
  data: any
): Promise<CreateAuthorizationV1SubjectAccessReviewResponse> => {
  data = ioK8sApiAuthorizationV1SubjectAccessReviewSchemaResponseTransformer(data);
  return data;
};

const ioK8sApiAuthorizationV1SubjectAccessReviewSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  return data;
};
