// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateCrmMiloapisComV1Alpha1NoteData,
  CreateCrmMiloapisComV1Alpha1NoteErrors,
  CreateCrmMiloapisComV1Alpha1NoteResponses,
  DeleteCrmMiloapisComV1Alpha1CollectionNoteData,
  DeleteCrmMiloapisComV1Alpha1CollectionNoteErrors,
  DeleteCrmMiloapisComV1Alpha1CollectionNoteResponses,
  DeleteCrmMiloapisComV1Alpha1NoteData,
  DeleteCrmMiloapisComV1Alpha1NoteErrors,
  DeleteCrmMiloapisComV1Alpha1NoteResponses,
  ListCrmMiloapisComV1Alpha1NoteData,
  ListCrmMiloapisComV1Alpha1NoteErrors,
  ListCrmMiloapisComV1Alpha1NoteResponses,
  PatchCrmMiloapisComV1Alpha1NoteData,
  PatchCrmMiloapisComV1Alpha1NoteErrors,
  PatchCrmMiloapisComV1Alpha1NoteResponses,
  PatchCrmMiloapisComV1Alpha1NoteStatusData,
  PatchCrmMiloapisComV1Alpha1NoteStatusErrors,
  PatchCrmMiloapisComV1Alpha1NoteStatusResponses,
  ReadCrmMiloapisComV1Alpha1NoteData,
  ReadCrmMiloapisComV1Alpha1NoteErrors,
  ReadCrmMiloapisComV1Alpha1NoteResponses,
  ReadCrmMiloapisComV1Alpha1NoteStatusData,
  ReadCrmMiloapisComV1Alpha1NoteStatusErrors,
  ReadCrmMiloapisComV1Alpha1NoteStatusResponses,
  ReplaceCrmMiloapisComV1Alpha1NoteData,
  ReplaceCrmMiloapisComV1Alpha1NoteErrors,
  ReplaceCrmMiloapisComV1Alpha1NoteResponses,
  ReplaceCrmMiloapisComV1Alpha1NoteStatusData,
  ReplaceCrmMiloapisComV1Alpha1NoteStatusErrors,
  ReplaceCrmMiloapisComV1Alpha1NoteStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of Note
 */
export const deleteCrmMiloapisComV1Alpha1CollectionNote = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteCrmMiloapisComV1Alpha1CollectionNoteData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteCrmMiloapisComV1Alpha1CollectionNoteResponses,
    DeleteCrmMiloapisComV1Alpha1CollectionNoteErrors,
    ThrowOnError
  >({ url: '/apis/crm.miloapis.com/v1alpha1/notes', ...options });

/**
 * list objects of kind Note
 */
export const listCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options?: Options<ListCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListCrmMiloapisComV1Alpha1NoteResponses,
    ListCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({ url: '/apis/crm.miloapis.com/v1alpha1/notes', ...options });

/**
 * create a Note
 */
export const createCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options: Options<CreateCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCrmMiloapisComV1Alpha1NoteResponses,
    CreateCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Note
 */
export const deleteCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options: Options<DeleteCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteCrmMiloapisComV1Alpha1NoteResponses,
    DeleteCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Note
 */
export const readCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options: Options<ReadCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadCrmMiloapisComV1Alpha1NoteResponses,
    ReadCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({ url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}', ...options });

/**
 * partially update the specified Note
 */
export const patchCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options: Options<PatchCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchCrmMiloapisComV1Alpha1NoteResponses,
    PatchCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Note
 */
export const replaceCrmMiloapisComV1Alpha1Note = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceCrmMiloapisComV1Alpha1NoteData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceCrmMiloapisComV1Alpha1NoteResponses,
    ReplaceCrmMiloapisComV1Alpha1NoteErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Note
 */
export const readCrmMiloapisComV1Alpha1NoteStatus = <ThrowOnError extends boolean = false>(
  options: Options<ReadCrmMiloapisComV1Alpha1NoteStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadCrmMiloapisComV1Alpha1NoteStatusResponses,
    ReadCrmMiloapisComV1Alpha1NoteStatusErrors,
    ThrowOnError
  >({ url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}/status', ...options });

/**
 * partially update status of the specified Note
 */
export const patchCrmMiloapisComV1Alpha1NoteStatus = <ThrowOnError extends boolean = false>(
  options: Options<PatchCrmMiloapisComV1Alpha1NoteStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchCrmMiloapisComV1Alpha1NoteStatusResponses,
    PatchCrmMiloapisComV1Alpha1NoteStatusErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Note
 */
export const replaceCrmMiloapisComV1Alpha1NoteStatus = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceCrmMiloapisComV1Alpha1NoteStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceCrmMiloapisComV1Alpha1NoteStatusResponses,
    ReplaceCrmMiloapisComV1Alpha1NoteStatusErrors,
    ThrowOnError
  >({
    url: '/apis/crm.miloapis.com/v1alpha1/notes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
