apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: support-system

resources:
  - ../../base

components:
  - ../../components/namespace
  - ../../components/api-registration
  - ../../components/cert-manager-ca

images:
  - name: ghcr.io/datum-cloud/support
    newTag: dev
