//go:build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy returns a deep copy of this ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportMessage) DeepCopyInto(out *SupportMessage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this SupportMessage.
func (in *SupportMessage) DeepCopy() *SupportMessage {
	if in == nil {
		return nil
	}
	out := new(SupportMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *SupportMessage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportMessageList) DeepCopyInto(out *SupportMessageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupportMessage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this SupportMessageList.
func (in *SupportMessageList) DeepCopy() *SupportMessageList {
	if in == nil {
		return nil
	}
	out := new(SupportMessageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *SupportMessageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportMessageSpec) DeepCopyInto(out *SupportMessageSpec) {
	*out = *in
	out.AuthorRef = in.AuthorRef
}

// DeepCopy returns a deep copy of this SupportMessageSpec.
func (in *SupportMessageSpec) DeepCopy() *SupportMessageSpec {
	if in == nil {
		return nil
	}
	out := new(SupportMessageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportMessageStatus) DeepCopyInto(out *SupportMessageStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of this SupportMessageStatus.
func (in *SupportMessageStatus) DeepCopy() *SupportMessageStatus {
	if in == nil {
		return nil
	}
	out := new(SupportMessageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportTicket) DeepCopyInto(out *SupportTicket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this SupportTicket.
func (in *SupportTicket) DeepCopy() *SupportTicket {
	if in == nil {
		return nil
	}
	out := new(SupportTicket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *SupportTicket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportTicketList) DeepCopyInto(out *SupportTicketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupportTicket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this SupportTicketList.
func (in *SupportTicketList) DeepCopy() *SupportTicketList {
	if in == nil {
		return nil
	}
	out := new(SupportTicketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *SupportTicketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportTicketSpec) DeepCopyInto(out *SupportTicketSpec) {
	*out = *in
	if in.OwnerRef != nil {
		in, out := &in.OwnerRef, &out.OwnerRef
		*out = new(UserReference)
		**out = **in
	}
	if in.Contributors != nil {
		in, out := &in.Contributors, &out.Contributors
		*out = make([]UserReference, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationRef != nil {
		in, out := &in.OrganizationRef, &out.OrganizationRef
		*out = new(ObjectReference)
		**out = **in
	}
	out.ReporterRef = in.ReporterRef
}

// DeepCopy returns a deep copy of this SupportTicketSpec.
func (in *SupportTicketSpec) DeepCopy() *SupportTicketSpec {
	if in == nil {
		return nil
	}
	out := new(SupportTicketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *SupportTicketStatus) DeepCopyInto(out *SupportTicketStatus) {
	*out = *in
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this SupportTicketStatus.
func (in *SupportTicketStatus) DeepCopy() *SupportTicketStatus {
	if in == nil {
		return nil
	}
	out := new(SupportTicketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *UserReference) DeepCopyInto(out *UserReference) {
	*out = *in
}

// DeepCopy returns a deep copy of this UserReference.
func (in *UserReference) DeepCopy() *UserReference {
	if in == nil {
		return nil
	}
	out := new(UserReference)
	in.DeepCopyInto(out)
	return out
}
