// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateNetworkingDatumapisComV1AlphaNamespacedDomainData,
  CreateNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedLocationData,
  CreateNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetResponses,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyData,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyErrors,
  DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedDomainData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedLocationData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedDomainData,
  ListNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedLocationData,
  ListNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesResponses,
  ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesData,
  ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesErrors,
  ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainData,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationData,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
  PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainData,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationData,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
  ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
  ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind Domain
 */
export const listNetworkingDatumapisComV1AlphaDomainForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaDomainForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/domains', ...options });

/**
 * list objects of kind HTTPProxy
 */
export const listNetworkingDatumapisComV1AlphaHttpProxyForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaHttpProxyForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/httpproxies', ...options });

/**
 * list objects of kind Location
 */
export const listNetworkingDatumapisComV1AlphaLocationForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaLocationForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/locations', ...options });

/**
 * delete collection of Domain
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedDomainErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains', ...options });

/**
 * list objects of kind Domain
 */
export const listNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains', ...options });

/**
 * create a Domain
 */
export const createNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Domain
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Domain
 */
export const readNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}',
    ...options,
  });

/**
 * partially update the specified Domain
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Domain
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedDomain = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Domain
 */
export const readNetworkingDatumapisComV1AlphaNamespacedDomainStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Domain
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedDomainStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Domain
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedDomainStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedDomainStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/domains/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of HTTPProxy
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies',
    ...options,
  });

/**
 * list objects of kind HTTPProxy
 */
export const listNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies',
    ...options,
  });

/**
 * create a HTTPProxy
 */
export const createNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a HTTPProxy
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified HTTPProxy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}',
    ...options,
  });

/**
 * partially update the specified HTTPProxy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified HTTPProxy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedHttpProxy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified HTTPProxy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified HTTPProxy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified HTTPProxy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedHttpProxyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/httpproxies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Location
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedLocationErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations', ...options });

/**
 * list objects of kind Location
 */
export const listNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations', ...options });

/**
 * create a Location
 */
export const createNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Location
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Location
 */
export const readNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}',
    ...options,
  });

/**
 * partially update the specified Location
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Location
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedLocation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Location
 */
export const readNetworkingDatumapisComV1AlphaNamespacedLocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Location
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedLocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Location
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedLocationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedLocationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/locations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of NetworkBinding
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings',
    ...options,
  });

/**
 * list objects of kind NetworkBinding
 */
export const listNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings',
    ...options,
  });

/**
 * create a NetworkBinding
 */
export const createNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a NetworkBinding
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified NetworkBinding
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}',
    ...options,
  });

/**
 * partially update the specified NetworkBinding
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified NetworkBinding
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkBinding = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified NetworkBinding
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified NetworkBinding
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified NetworkBinding
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkBindingStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of NetworkContext
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts',
    ...options,
  });

/**
 * list objects of kind NetworkContext
 */
export const listNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts',
    ...options,
  });

/**
 * create a NetworkContext
 */
export const createNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a NetworkContext
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified NetworkContext
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}',
    ...options,
  });

/**
 * partially update the specified NetworkContext
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified NetworkContext
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkContext = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified NetworkContext
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified NetworkContext
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified NetworkContext
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkContextStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkcontexts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of NetworkPolicy
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies',
    ...options,
  });

/**
 * list objects of kind NetworkPolicy
 */
export const listNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies',
    ...options,
  });

/**
 * create a NetworkPolicy
 */
export const createNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a NetworkPolicy
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified NetworkPolicy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}',
    ...options,
  });

/**
 * partially update the specified NetworkPolicy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified NetworkPolicy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified NetworkPolicy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified NetworkPolicy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified NetworkPolicy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networkpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Network
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedNetworkErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks', ...options });

/**
 * list objects of kind Network
 */
export const listNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks', ...options });

/**
 * create a Network
 */
export const createNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Network
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Network
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}',
    ...options,
  });

/**
 * partially update the specified Network
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Network
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetwork = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Network
 */
export const readNetworkingDatumapisComV1AlphaNamespacedNetworkStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Network
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedNetworkStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Network
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedNetworkStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/networks/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of SubnetClaim
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims',
    ...options,
  });

/**
 * list objects of kind SubnetClaim
 */
export const listNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims',
    ...options,
  });

/**
 * create a SubnetClaim
 */
export const createNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a SubnetClaim
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified SubnetClaim
 */
export const readNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}',
    ...options,
  });

/**
 * partially update the specified SubnetClaim
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified SubnetClaim
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified SubnetClaim
 */
export const readNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified SubnetClaim
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified SubnetClaim
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetClaimStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnetclaims/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Subnet
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedSubnetErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets', ...options });

/**
 * list objects of kind Subnet
 */
export const listNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets', ...options });

/**
 * create a Subnet
 */
export const createNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Subnet
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Subnet
 */
export const readNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}',
    ...options,
  });

/**
 * partially update the specified Subnet
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Subnet
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Subnet
 */
export const readNetworkingDatumapisComV1AlphaNamespacedSubnetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Subnet
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedSubnetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Subnet
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedSubnetStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/subnets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of TrafficProtectionPolicy
 */
export const deleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyResponses,
    DeleteNetworkingDatumapisComV1AlphaCollectionNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies',
    ...options,
  });

/**
 * list objects of kind TrafficProtectionPolicy
 */
export const listNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    ListNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies',
    ...options,
  });

/**
 * create a TrafficProtectionPolicy
 */
export const createNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    CreateNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a TrafficProtectionPolicy
 */
export const deleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    DeleteNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified TrafficProtectionPolicy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}',
    ...options,
  });

/**
 * partially update the specified TrafficProtectionPolicy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified TrafficProtectionPolicy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified TrafficProtectionPolicy
 */
export const readNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
    ReadNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified TrafficProtectionPolicy
 */
export const patchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
    PatchNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified TrafficProtectionPolicy
 */
export const replaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusResponses,
    ReplaceNetworkingDatumapisComV1AlphaNamespacedTrafficProtectionPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/networking.datumapis.com/v1alpha/namespaces/{namespace}/trafficprotectionpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * list objects of kind NetworkBinding
 */
export const listNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaNetworkBindingForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/networkbindings', ...options });

/**
 * list objects of kind NetworkContext
 */
export const listNetworkingDatumapisComV1AlphaNetworkContextForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaNetworkContextForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/networkcontexts', ...options });

/**
 * list objects of kind NetworkPolicy
 */
export const listNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaNetworkPolicyForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/networkpolicies', ...options });

/**
 * list objects of kind Network
 */
export const listNetworkingDatumapisComV1AlphaNetworkForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaNetworkForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/networks', ...options });

/**
 * list objects of kind SubnetClaim
 */
export const listNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaSubnetClaimForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/subnetclaims', ...options });

/**
 * list objects of kind Subnet
 */
export const listNetworkingDatumapisComV1AlphaSubnetForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaSubnetForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/subnets', ...options });

/**
 * list objects of kind TrafficProtectionPolicy
 */
export const listNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesResponses,
    ListNetworkingDatumapisComV1AlphaTrafficProtectionPolicyForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/networking.datumapis.com/v1alpha/trafficprotectionpolicies', ...options });
