// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentData,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentErrors,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentResponses,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionData,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionErrors,
  DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionResponses,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesData,
  ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesErrors,
  ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesResponses,
  ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesData,
  ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesErrors,
  ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesResponses,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
  PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
  ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentData,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
  ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind DocumentRevision
 */
export const listDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesResponses,
    ListDocumentationMiloapisComV1Alpha1DocumentRevisionForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/documentation.miloapis.com/v1alpha1/documentrevisions', ...options });

/**
 * list objects of kind Document
 */
export const listDocumentationMiloapisComV1Alpha1DocumentForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesResponses,
    ListDocumentationMiloapisComV1Alpha1DocumentForAllNamespacesErrors,
    ThrowOnError
  >({ url: '/apis/documentation.miloapis.com/v1alpha1/documents', ...options });

/**
 * delete collection of DocumentRevision
 */
export const deleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionResponses,
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions',
    ...options,
  });

/**
 * list objects of kind DocumentRevision
 */
export const listDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    ListDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions',
    ...options,
  });

/**
 * create a DocumentRevision
 */
export const createDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a DocumentRevision
 */
export const deleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified DocumentRevision
 */
export const readDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}',
    ...options,
  });

/**
 * partially update the specified DocumentRevision
 */
export const patchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified DocumentRevision
 */
export const replaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionResponses,
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified DocumentRevision
 */
export const readDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified DocumentRevision
 */
export const patchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified DocumentRevision
 */
export const replaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusResponses,
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentRevisionStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documentrevisions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Document
 */
export const deleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentResponses,
    DeleteDocumentationMiloapisComV1Alpha1CollectionNamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents',
    ...options,
  });

/**
 * list objects of kind Document
 */
export const listDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    ListDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents',
    ...options,
  });

/**
 * create a Document
 */
export const createDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    CreateDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Document
 */
export const deleteDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    DeleteDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Document
 */
export const readDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}',
    ...options,
  });

/**
 * partially update the specified Document
 */
export const patchDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Document
 */
export const replaceDocumentationMiloapisComV1Alpha1NamespacedDocument = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentResponses,
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Document
 */
export const readDocumentationMiloapisComV1Alpha1NamespacedDocumentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
    ReadDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Document
 */
export const patchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
    PatchDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Document
 */
export const replaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusResponses,
    ReplaceDocumentationMiloapisComV1Alpha1NamespacedDocumentStatusErrors,
    ThrowOnError
  >({
    url: '/apis/documentation.miloapis.com/v1alpha1/namespaces/{namespace}/documents/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
