// This file is auto-generated by @hey-api/openapi-ts
import type { Options as ClientOptions, TDataShape, Client } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  CreateQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  CreateQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  CreateQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyData,
  DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyData,
  DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketData,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimData,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantData,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantResponses,
  DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationData,
  DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationErrors,
  DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationResponses,
  DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesData,
  ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesErrors,
  ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesResponses,
  ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  ListQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  ListQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  ListQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesData,
  ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesErrors,
  ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesResponses,
  ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesData,
  ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesErrors,
  ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesResponses,
  ListQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  ListQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  ListQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyData,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyData,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationData,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind AllowanceBucket
 */
export const listQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesResponses,
    ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/allowancebuckets',
    ...options,
  });
};

/**
 * delete collection of ClaimCreationPolicy
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies',
    ...options,
  });
};

/**
 * list objects of kind ClaimCreationPolicy
 */
export const listQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies',
    ...options,
  });
};

/**
 * create a ClaimCreationPolicy
 */
export const createQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a ClaimCreationPolicy
 */
export const deleteQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified ClaimCreationPolicy
 */
export const readQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}',
    ...options,
  });
};

/**
 * partially update the specified ClaimCreationPolicy
 */
export const patchQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified ClaimCreationPolicy
 */
export const replaceQuotaMiloapisComV1Alpha1ClaimCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponses,
    ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified ClaimCreationPolicy
 */
export const readQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
    ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified ClaimCreationPolicy
 */
export const patchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
    PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified ClaimCreationPolicy
 */
export const replaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/claimcreationpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of GrantCreationPolicy
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies',
    ...options,
  });
};

/**
 * list objects of kind GrantCreationPolicy
 */
export const listQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    ListQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies',
    ...options,
  });
};

/**
 * create a GrantCreationPolicy
 */
export const createQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a GrantCreationPolicy
 */
export const deleteQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified GrantCreationPolicy
 */
export const readQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}',
    ...options,
  });
};

/**
 * partially update the specified GrantCreationPolicy
 */
export const patchQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified GrantCreationPolicy
 */
export const replaceQuotaMiloapisComV1Alpha1GrantCreationPolicy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyResponses,
    ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified GrantCreationPolicy
 */
export const readQuotaMiloapisComV1Alpha1GrantCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
    ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified GrantCreationPolicy
 */
export const patchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
    PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified GrantCreationPolicy
 */
export const replaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/grantcreationpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of AllowanceBucket
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets',
    ...options,
  });
};

/**
 * list objects of kind AllowanceBucket
 */
export const listQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets',
    ...options,
  });
};

/**
 * create an AllowanceBucket
 */
export const createQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete an AllowanceBucket
 */
export const deleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified AllowanceBucket
 */
export const readQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}',
    ...options,
  });
};

/**
 * partially update the specified AllowanceBucket
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified AllowanceBucket
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucket = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified AllowanceBucket
 */
export const readQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified AllowanceBucket
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified AllowanceBucket
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/allowancebuckets/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of ResourceClaim
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims',
    ...options,
  });
};

/**
 * list objects of kind ResourceClaim
 */
export const listQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims',
    ...options,
  });
};

/**
 * create a ResourceClaim
 */
export const createQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a ResourceClaim
 */
export const deleteQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified ResourceClaim
 */
export const readQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}',
    ...options,
  });
};

/**
 * partially update the specified ResourceClaim
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified ResourceClaim
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceClaim = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified ResourceClaim
 */
export const readQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified ResourceClaim
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified ResourceClaim
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourceclaims/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete collection of ResourceGrant
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantData,
    ThrowOnError
  >
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants',
    ...options,
  });
};

/**
 * list objects of kind ResourceGrant
 */
export const listQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants',
    ...options,
  });
};

/**
 * create a ResourceGrant
 */
export const createQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a ResourceGrant
 */
export const deleteQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified ResourceGrant
 */
export const readQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}',
    ...options,
  });
};

/**
 * partially update the specified ResourceGrant
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified ResourceGrant
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceGrant = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified ResourceGrant
 */
export const readQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
    ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified ResourceGrant
 */
export const patchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
    PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified ResourceGrant
 */
export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/namespaces/{namespace}/resourcegrants/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * list objects of kind ResourceClaim
 */
export const listQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesResponses,
    ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceclaims',
    ...options,
  });
};

/**
 * list objects of kind ResourceGrant
 */
export const listQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespaces = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesResponses,
    ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourcegrants',
    ...options,
  });
};

/**
 * delete collection of ResourceRegistration
 */
export const deleteQuotaMiloapisComV1Alpha1CollectionResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationResponses,
    DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations',
    ...options,
  });
};

/**
 * list objects of kind ResourceRegistration
 */
export const listQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ListQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    ListQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations',
    ...options,
  });
};

/**
 * create a ResourceRegistration
 */
export const createQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    CreateQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    CreateQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * delete a ResourceRegistration
 */
export const deleteQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read the specified ResourceRegistration
 */
export const readQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    ReadQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}',
    ...options,
  });
};

/**
 * partially update the specified ResourceRegistration
 */
export const patchQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    PatchQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace the specified ResourceRegistration
 */
export const replaceQuotaMiloapisComV1Alpha1ResourceRegistration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationResponses,
    ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * read status of the specified ResourceRegistration
 */
export const readQuotaMiloapisComV1Alpha1ResourceRegistrationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
    ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}/status',
    ...options,
  });
};

/**
 * partially update status of the specified ResourceRegistration
 */
export const patchQuotaMiloapisComV1Alpha1ResourceRegistrationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).patch<
    PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
    PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });
};

/**
 * replace status of the specified ResourceRegistration
 */
export const replaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponses,
    ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/quota.miloapis.com/v1alpha1/resourceregistrations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};
