// This file is auto-generated by @hey-api/openapi-ts
import type {
  CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  CreateQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantResponse,
  DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationResponse,
  DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesResponse,
  ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  ListQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesResponse,
  ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesResponse,
  ListQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse,
  ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse,
  ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse,
  ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationResponse,
  ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse,
} from './types.gen';

export const listQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesResponseTransformer =
  async (
    data: any
  ): Promise<ListQuotaMiloapisComV1Alpha1AllowanceBucketForAllNamespacesResponse> => {
    data = comMiloapisQuotaV1Alpha1AllowanceBucketListSchemaResponseTransformer(data);
    return data;
  };

const comMiloapisQuotaV1Alpha1AllowanceBucketListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  if (data.status) {
    data.status.allocated = BigInt(data.status.allocated.toString());
    data.status.available = BigInt(data.status.available.toString());
    if (data.status.contributingGrantRefs) {
      data.status.contributingGrantRefs = data.status.contributingGrantRefs.map((item: any) => {
        item.amount = BigInt(item.amount.toString());
        item.lastObservedGeneration = BigInt(item.lastObservedGeneration.toString());
        return item;
      });
    }
    if (data.status.lastReconciliation) {
      data.status.lastReconciliation = new Date(data.status.lastReconciliation);
    }
    data.status.limit = BigInt(data.status.limit.toString());
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer = (data: any) => {
  if (data.creationTimestamp) {
    data.creationTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.creationTimestamp
    );
  }
  if (data.deletionGracePeriodSeconds) {
    data.deletionGracePeriodSeconds = BigInt(data.deletionGracePeriodSeconds.toString());
  }
  if (data.deletionTimestamp) {
    data.deletionTimestamp = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(
      data.deletionTimestamp
    );
  }
  if (data.generation) {
    data.generation = BigInt(data.generation.toString());
  }
  if (data.managedFields) {
    data.managedFields = data.managedFields.map((item: any) => {
      return ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer(item);
    });
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer = (data: any) => {
  data = new Date(data);
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ManagedFieldsEntrySchemaResponseTransformer = (data: any) => {
  if (data.time) {
    data.time = ioK8sApimachineryPkgApisMetaV1TimeSchemaResponseTransformer(data.time);
  }
  return data;
};

const ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer = (data: any) => {
  if (data.remainingItemCount) {
    data.remainingItemCount = BigInt(data.remainingItemCount.toString());
  }
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionClaimCreationPolicyResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

const ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

export const listQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicyListSchemaResponseTransformer(data);
  return data;
};

const comMiloapisQuotaV1Alpha1ClaimCreationPolicyListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  data.spec.target.resourceClaimTemplate.spec.requests =
    data.spec.target.resourceClaimTemplate.spec.requests.map((item: any) => {
      item.amount = BigInt(item.amount.toString());
      return item;
    });
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

export const createQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1ClaimCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ClaimCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionGrantCreationPolicyResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicyListSchemaResponseTransformer(data);
  return data;
};

const comMiloapisQuotaV1Alpha1GrantCreationPolicyListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  data.spec.target.resourceGrantTemplate.spec.allowances =
    data.spec.target.resourceGrantTemplate.spec.allowances.map((item: any) => {
      item.buckets = item.buckets.map((item: any) => {
        item.amount = BigInt(item.amount.toString());
        return item;
      });
      return item;
    });
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

export const createQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1GrantCreationPolicyResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1GrantCreationPolicyStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1GrantCreationPolicySchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedAllowanceBucketResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = comMiloapisQuotaV1Alpha1AllowanceBucketListSchemaResponseTransformer(data);
  return data;
};

export const createQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketResponse> => {
  data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse> => {
    data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
    return data;
  };

export const patchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponseTransformer =
  async (
    data: any
  ): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse> => {
    data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
    return data;
  };

export const replaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedAllowanceBucketStatusResponse> => {
    data = comMiloapisQuotaV1Alpha1AllowanceBucketSchemaResponseTransformer(data);
    return data;
  };

export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceClaimResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimListSchemaResponseTransformer(data);
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceClaimListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  data.spec.requests = data.spec.requests.map((item: any) => {
    item.amount = BigInt(item.amount.toString());
    return item;
  });
  if (data.status) {
    if (data.status.allocations) {
      data.status.allocations = data.status.allocations.map((item: any) => {
        if (item.allocatedAmount) {
          item.allocatedAmount = BigInt(item.allocatedAmount.toString());
        }
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        return item;
      });
    }
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

export const createQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceClaimStatusResponse> => {
    data = comMiloapisQuotaV1Alpha1ResourceClaimSchemaResponseTransformer(data);
    return data;
  };

export const deleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionNamespacedResourceGrantResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantListSchemaResponseTransformer(data);
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceGrantListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  data.spec.allowances = data.spec.allowances.map((item: any) => {
    item.buckets = item.buckets.map((item: any) => {
      item.amount = BigInt(item.amount.toString());
      return item;
    });
    return item;
  });
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

export const createQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponseTransformer =
  async (
    data: any
  ): Promise<ReplaceQuotaMiloapisComV1Alpha1NamespacedResourceGrantStatusResponse> => {
    data = comMiloapisQuotaV1Alpha1ResourceGrantSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1ResourceClaimForAllNamespacesResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceClaimListSchemaResponseTransformer(data);
  return data;
};

export const listQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1ResourceGrantForAllNamespacesResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceGrantListSchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationResponseTransformer =
  async (
    data: any
  ): Promise<DeleteQuotaMiloapisComV1Alpha1CollectionResourceRegistrationResponse> => {
    data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
    return data;
  };

export const listQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<ListQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationListSchemaResponseTransformer(data);
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceRegistrationListSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(item);
  });
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ListMetaSchemaResponseTransformer(data.metadata);
  }
  return data;
};

const comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer = (data: any) => {
  if (data.metadata) {
    data.metadata = ioK8sApimachineryPkgApisMetaV1ObjectMetaSchemaResponseTransformer(
      data.metadata
    );
  }
  data.spec.unitConversionFactor = BigInt(data.spec.unitConversionFactor.toString());
  if (data.status) {
    if (data.status.conditions) {
      data.status.conditions = data.status.conditions.map((item: any) => {
        item.lastTransitionTime = new Date(item.lastTransitionTime);
        if (item.observedGeneration) {
          item.observedGeneration = BigInt(item.observedGeneration.toString());
        }
        return item;
      });
    }
    if (data.status.observedGeneration) {
      data.status.observedGeneration = BigInt(data.status.observedGeneration.toString());
    }
  }
  return data;
};

export const createQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<CreateQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const deleteQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<DeleteQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = ioK8sApimachineryPkgApisMetaV1StatusSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1ResourceRegistrationResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const readQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponseTransformer = async (
  data: any
): Promise<ReadQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const patchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponseTransformer = async (
  data: any
): Promise<PatchQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};

export const replaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponseTransformer = async (
  data: any
): Promise<ReplaceQuotaMiloapisComV1Alpha1ResourceRegistrationStatusResponse> => {
  data = comMiloapisQuotaV1Alpha1ResourceRegistrationSchemaResponseTransformer(data);
  return data;
};
