// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateFraudMiloapisComV1Alpha1FraudEvaluationData,
  CreateFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  CreateFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  CreateFraudMiloapisComV1Alpha1FraudPolicyData,
  CreateFraudMiloapisComV1Alpha1FraudPolicyErrors,
  CreateFraudMiloapisComV1Alpha1FraudPolicyResponses,
  CreateFraudMiloapisComV1Alpha1FraudProviderData,
  CreateFraudMiloapisComV1Alpha1FraudProviderErrors,
  CreateFraudMiloapisComV1Alpha1FraudProviderResponses,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationData,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationErrors,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationResponses,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyData,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyErrors,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyResponses,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderData,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderErrors,
  DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderResponses,
  DeleteFraudMiloapisComV1Alpha1FraudEvaluationData,
  DeleteFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  DeleteFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  DeleteFraudMiloapisComV1Alpha1FraudPolicyData,
  DeleteFraudMiloapisComV1Alpha1FraudPolicyErrors,
  DeleteFraudMiloapisComV1Alpha1FraudPolicyResponses,
  DeleteFraudMiloapisComV1Alpha1FraudProviderData,
  DeleteFraudMiloapisComV1Alpha1FraudProviderErrors,
  DeleteFraudMiloapisComV1Alpha1FraudProviderResponses,
  ListFraudMiloapisComV1Alpha1FraudEvaluationData,
  ListFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  ListFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  ListFraudMiloapisComV1Alpha1FraudPolicyData,
  ListFraudMiloapisComV1Alpha1FraudPolicyErrors,
  ListFraudMiloapisComV1Alpha1FraudPolicyResponses,
  ListFraudMiloapisComV1Alpha1FraudProviderData,
  ListFraudMiloapisComV1Alpha1FraudProviderErrors,
  ListFraudMiloapisComV1Alpha1FraudProviderResponses,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationData,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusData,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
  PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
  PatchFraudMiloapisComV1Alpha1FraudPolicyData,
  PatchFraudMiloapisComV1Alpha1FraudPolicyErrors,
  PatchFraudMiloapisComV1Alpha1FraudPolicyResponses,
  PatchFraudMiloapisComV1Alpha1FraudPolicyStatusData,
  PatchFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
  PatchFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
  PatchFraudMiloapisComV1Alpha1FraudProviderData,
  PatchFraudMiloapisComV1Alpha1FraudProviderErrors,
  PatchFraudMiloapisComV1Alpha1FraudProviderResponses,
  PatchFraudMiloapisComV1Alpha1FraudProviderStatusData,
  PatchFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
  PatchFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationData,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusData,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
  ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
  ReadFraudMiloapisComV1Alpha1FraudPolicyData,
  ReadFraudMiloapisComV1Alpha1FraudPolicyErrors,
  ReadFraudMiloapisComV1Alpha1FraudPolicyResponses,
  ReadFraudMiloapisComV1Alpha1FraudPolicyStatusData,
  ReadFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
  ReadFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
  ReadFraudMiloapisComV1Alpha1FraudProviderData,
  ReadFraudMiloapisComV1Alpha1FraudProviderErrors,
  ReadFraudMiloapisComV1Alpha1FraudProviderResponses,
  ReadFraudMiloapisComV1Alpha1FraudProviderStatusData,
  ReadFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
  ReadFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationData,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusData,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyData,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusData,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderData,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderResponses,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusData,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
  ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of FraudEvaluation
 */
export const deleteFraudMiloapisComV1Alpha1CollectionFraudEvaluation = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationResponses,
    DeleteFraudMiloapisComV1Alpha1CollectionFraudEvaluationErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations', ...options });

/**
 * list objects of kind FraudEvaluation
 */
export const listFraudMiloapisComV1Alpha1FraudEvaluation = <ThrowOnError extends boolean = false>(
  options?: Options<ListFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    ListFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations', ...options });

/**
 * create a FraudEvaluation
 */
export const createFraudMiloapisComV1Alpha1FraudEvaluation = <ThrowOnError extends boolean = false>(
  options: Options<CreateFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    CreateFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a FraudEvaluation
 */
export const deleteFraudMiloapisComV1Alpha1FraudEvaluation = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    DeleteFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified FraudEvaluation
 */
export const readFraudMiloapisComV1Alpha1FraudEvaluation = <ThrowOnError extends boolean = false>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    ReadFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}', ...options });

/**
 * partially update the specified FraudEvaluation
 */
export const patchFraudMiloapisComV1Alpha1FraudEvaluation = <ThrowOnError extends boolean = false>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    PatchFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified FraudEvaluation
 */
export const replaceFraudMiloapisComV1Alpha1FraudEvaluation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudEvaluationData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudEvaluationResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudEvaluationErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified FraudEvaluation
 */
export const readFraudMiloapisComV1Alpha1FraudEvaluationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
    ReadFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}/status', ...options });

/**
 * partially update status of the specified FraudEvaluation
 */
export const patchFraudMiloapisComV1Alpha1FraudEvaluationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
    PatchFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified FraudEvaluation
 */
export const replaceFraudMiloapisComV1Alpha1FraudEvaluationStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudEvaluationStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudevaluations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of FraudPolicy
 */
export const deleteFraudMiloapisComV1Alpha1CollectionFraudPolicy = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyResponses,
    DeleteFraudMiloapisComV1Alpha1CollectionFraudPolicyErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies', ...options });

/**
 * list objects of kind FraudPolicy
 */
export const listFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options?: Options<ListFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListFraudMiloapisComV1Alpha1FraudPolicyResponses,
    ListFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies', ...options });

/**
 * create a FraudPolicy
 */
export const createFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options: Options<CreateFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateFraudMiloapisComV1Alpha1FraudPolicyResponses,
    CreateFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a FraudPolicy
 */
export const deleteFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1FraudPolicyResponses,
    DeleteFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified FraudPolicy
 */
export const readFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudPolicyResponses,
    ReadFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}', ...options });

/**
 * partially update the specified FraudPolicy
 */
export const patchFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudPolicyResponses,
    PatchFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified FraudPolicy
 */
export const replaceFraudMiloapisComV1Alpha1FraudPolicy = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudPolicyData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudPolicyResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudPolicyErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified FraudPolicy
 */
export const readFraudMiloapisComV1Alpha1FraudPolicyStatus = <ThrowOnError extends boolean = false>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudPolicyStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
    ReadFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}/status', ...options });

/**
 * partially update status of the specified FraudPolicy
 */
export const patchFraudMiloapisComV1Alpha1FraudPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudPolicyStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
    PatchFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified FraudPolicy
 */
export const replaceFraudMiloapisComV1Alpha1FraudPolicyStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudPolicyStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudpolicies/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of FraudProvider
 */
export const deleteFraudMiloapisComV1Alpha1CollectionFraudProvider = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderResponses,
    DeleteFraudMiloapisComV1Alpha1CollectionFraudProviderErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders', ...options });

/**
 * list objects of kind FraudProvider
 */
export const listFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options?: Options<ListFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListFraudMiloapisComV1Alpha1FraudProviderResponses,
    ListFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders', ...options });

/**
 * create a FraudProvider
 */
export const createFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options: Options<CreateFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateFraudMiloapisComV1Alpha1FraudProviderResponses,
    CreateFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a FraudProvider
 */
export const deleteFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteFraudMiloapisComV1Alpha1FraudProviderResponses,
    DeleteFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified FraudProvider
 */
export const readFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudProviderResponses,
    ReadFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}', ...options });

/**
 * partially update the specified FraudProvider
 */
export const patchFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudProviderResponses,
    PatchFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified FraudProvider
 */
export const replaceFraudMiloapisComV1Alpha1FraudProvider = <ThrowOnError extends boolean = false>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudProviderData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudProviderResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudProviderErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified FraudProvider
 */
export const readFraudMiloapisComV1Alpha1FraudProviderStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadFraudMiloapisComV1Alpha1FraudProviderStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
    ReadFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
    ThrowOnError
  >({ url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}/status', ...options });

/**
 * partially update status of the specified FraudProvider
 */
export const patchFraudMiloapisComV1Alpha1FraudProviderStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchFraudMiloapisComV1Alpha1FraudProviderStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
    PatchFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified FraudProvider
 */
export const replaceFraudMiloapisComV1Alpha1FraudProviderStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusResponses,
    ReplaceFraudMiloapisComV1Alpha1FraudProviderStatusErrors,
    ThrowOnError
  >({
    url: '/apis/fraud.miloapis.com/v1alpha1/fraudproviders/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
