// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../shared/client';
import { client } from '../shared/client.gen';
import type {
  CreateApiextensionsV1CustomResourceDefinitionData,
  CreateApiextensionsV1CustomResourceDefinitionErrors,
  CreateApiextensionsV1CustomResourceDefinitionResponses,
  DeleteApiextensionsV1CollectionCustomResourceDefinitionData,
  DeleteApiextensionsV1CollectionCustomResourceDefinitionErrors,
  DeleteApiextensionsV1CollectionCustomResourceDefinitionResponses,
  DeleteApiextensionsV1CustomResourceDefinitionData,
  DeleteApiextensionsV1CustomResourceDefinitionErrors,
  DeleteApiextensionsV1CustomResourceDefinitionResponses,
  GetApiextensionsV1ApiResourcesData,
  GetApiextensionsV1ApiResourcesErrors,
  GetApiextensionsV1ApiResourcesResponses,
  ListApiextensionsV1CustomResourceDefinitionData,
  ListApiextensionsV1CustomResourceDefinitionErrors,
  ListApiextensionsV1CustomResourceDefinitionResponses,
  PatchApiextensionsV1CustomResourceDefinitionData,
  PatchApiextensionsV1CustomResourceDefinitionErrors,
  PatchApiextensionsV1CustomResourceDefinitionResponses,
  PatchApiextensionsV1CustomResourceDefinitionStatusData,
  PatchApiextensionsV1CustomResourceDefinitionStatusErrors,
  PatchApiextensionsV1CustomResourceDefinitionStatusResponses,
  ReadApiextensionsV1CustomResourceDefinitionData,
  ReadApiextensionsV1CustomResourceDefinitionErrors,
  ReadApiextensionsV1CustomResourceDefinitionResponses,
  ReadApiextensionsV1CustomResourceDefinitionStatusData,
  ReadApiextensionsV1CustomResourceDefinitionStatusErrors,
  ReadApiextensionsV1CustomResourceDefinitionStatusResponses,
  ReplaceApiextensionsV1CustomResourceDefinitionData,
  ReplaceApiextensionsV1CustomResourceDefinitionErrors,
  ReplaceApiextensionsV1CustomResourceDefinitionResponses,
  ReplaceApiextensionsV1CustomResourceDefinitionStatusData,
  ReplaceApiextensionsV1CustomResourceDefinitionStatusErrors,
  ReplaceApiextensionsV1CustomResourceDefinitionStatusResponses,
  WatchApiextensionsV1CustomResourceDefinitionData,
  WatchApiextensionsV1CustomResourceDefinitionErrors,
  WatchApiextensionsV1CustomResourceDefinitionListData,
  WatchApiextensionsV1CustomResourceDefinitionListErrors,
  WatchApiextensionsV1CustomResourceDefinitionListResponses,
  WatchApiextensionsV1CustomResourceDefinitionResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * get available resources
 */
export const getApiextensionsV1ApiResources = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiextensionsV1ApiResourcesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetApiextensionsV1ApiResourcesResponses,
    GetApiextensionsV1ApiResourcesErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/', ...options });

/**
 * delete collection of CustomResourceDefinition
 */
export const deleteApiextensionsV1CollectionCustomResourceDefinition = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<DeleteApiextensionsV1CollectionCustomResourceDefinitionData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteApiextensionsV1CollectionCustomResourceDefinitionResponses,
    DeleteApiextensionsV1CollectionCustomResourceDefinitionErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions',
    ...options,
    headers: {
      'Content-Type': '*/*',
      ...options?.headers,
    },
  });

/**
 * list or watch objects of kind CustomResourceDefinition
 */
export const listApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options?: Options<ListApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListApiextensionsV1CustomResourceDefinitionResponses,
    ListApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions', ...options });

/**
 * create a CustomResourceDefinition
 */
export const createApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateApiextensionsV1CustomResourceDefinitionResponses,
    CreateApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions',
    ...options,
    headers: {
      'Content-Type': '*/*',
      ...options.headers,
    },
  });

/**
 * delete a CustomResourceDefinition
 */
export const deleteApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiextensionsV1CustomResourceDefinitionResponses,
    DeleteApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': '*/*',
      ...options.headers,
    },
  });

/**
 * read the specified CustomResourceDefinition
 */
export const readApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options: Options<ReadApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadApiextensionsV1CustomResourceDefinitionResponses,
    ReadApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}', ...options });

/**
 * partially update the specified CustomResourceDefinition
 */
export const patchApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options: Options<PatchApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchApiextensionsV1CustomResourceDefinitionResponses,
    PatchApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified CustomResourceDefinition
 */
export const replaceApiextensionsV1CustomResourceDefinition = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceApiextensionsV1CustomResourceDefinitionResponses,
    ReplaceApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': '*/*',
      ...options.headers,
    },
  });

/**
 * read status of the specified CustomResourceDefinition
 */
export const readApiextensionsV1CustomResourceDefinitionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadApiextensionsV1CustomResourceDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadApiextensionsV1CustomResourceDefinitionStatusResponses,
    ReadApiextensionsV1CustomResourceDefinitionStatusErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status', ...options });

/**
 * partially update status of the specified CustomResourceDefinition
 */
export const patchApiextensionsV1CustomResourceDefinitionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchApiextensionsV1CustomResourceDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchApiextensionsV1CustomResourceDefinitionStatusResponses,
    PatchApiextensionsV1CustomResourceDefinitionStatusErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified CustomResourceDefinition
 */
export const replaceApiextensionsV1CustomResourceDefinitionStatus = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReplaceApiextensionsV1CustomResourceDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceApiextensionsV1CustomResourceDefinitionStatusResponses,
    ReplaceApiextensionsV1CustomResourceDefinitionStatusErrors,
    ThrowOnError
  >({
    url: '/apis/apiextensions.k8s.io/v1/customresourcedefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': '*/*',
      ...options.headers,
    },
  });

/**
 * watch individual changes to a list of CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead.
 */
export const watchApiextensionsV1CustomResourceDefinitionList = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<WatchApiextensionsV1CustomResourceDefinitionListData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    WatchApiextensionsV1CustomResourceDefinitionListResponses,
    WatchApiextensionsV1CustomResourceDefinitionListErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions', ...options });

/**
 * watch changes to an object of kind CustomResourceDefinition. deprecated: use the 'watch' parameter with a list operation instead, filtered to a single item with the 'fieldSelector' parameter.
 */
export const watchApiextensionsV1CustomResourceDefinition = <ThrowOnError extends boolean = false>(
  options: Options<WatchApiextensionsV1CustomResourceDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    WatchApiextensionsV1CustomResourceDefinitionResponses,
    WatchApiextensionsV1CustomResourceDefinitionErrors,
    ThrowOnError
  >({ url: '/apis/apiextensions.k8s.io/v1/watch/customresourcedefinitions/{name}', ...options });
